# Generated by Django 2.2 on 2020-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
