# Generated by Django 2.2 on 2020-04-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_is_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
