# Generated by Django 2.2 on 2020-04-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200429_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='upload/picture'),
        ),
    ]
