# Generated by Django 2.2 on 2020-04-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200429_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(blank=True, default='user.png', max_length=255, null=True, upload_to='upload/picture'),
        ),
    ]
