# Generated by Django 2.2 on 2020-07-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200430_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(choices=[('T', 'Tunis'), ('N', 'Nabeul'), ('A', 'Ariana')], max_length=128, null=True),
        ),
    ]
