# Generated by Django 2.2 on 2020-07-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200709_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, choices=[('T', 'Tunis'), ('N', 'Nabeul'), ('A', 'Ariana')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='specialite',
            field=models.CharField(blank=True, max_length=233, null=True),
        ),
    ]
