# Generated by Django 2.2 on 2020-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200709_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, choices=[('Tunis', 'Tunis'), ('Nabeul', 'Nabeul'), ('Ariana', 'Ariana'), ('Bezerte', 'Bezerte'), ('Autres', 'Autres')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=128),
        ),
    ]
