# Generated by Django 2.2 on 2020-05-04 03:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
