# Generated by Django 2.2 on 2020-04-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_disponibilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
