# Generated by Django 2.2 on 2020-04-26 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200420_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointment.Event'),
        ),
    ]
