# Generated by Django 2.2 on 2020-05-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20200426_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-pk']},
        ),
    ]
