# Generated by Django 2.2 on 2020-05-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20200502_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-pk'], 'verbose_name': 'Rendez-Vou'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='available',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
