# Generated by Django 2.2 on 2020-05-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20200528_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='available',
            field=models.BooleanField(null=True),
        ),
    ]
