# Generated by Django 2.2 on 2020-05-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200528_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationmateriel',
            options={'ordering': ['-pk']},
        ),
    ]
